workflows:
  ios-release:
    name: Sunaa App iOS Release
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      groups:
        - app_store_credentials 
    scripts:
      - name: Set up code signing
        script: | 
          keychain initialize
          app-store-connect fetch-signing-files "com.example.sunaaApp" --create
          keychain add-certificates
      - name: Get Flutter packages
        script: flutter pub get
      - name: Build iOS IPA
        script: | 
          flutter build ipa --release --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
    # حذفنا قسم النشر (publishing) من هنا لأنه هو مسبب المشكلة حالياً