workflows:
  ios-release:
    name: Sunaa App iOS Release
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      groups:
        - app_store_credentials 
    scripts:
      - name: Set up code signing
        script: | 
          keychain initialize
          # تحويل النص إلى ملف مؤقت لحل مشكلة unrecognized arguments
          echo "$APP_STORE_CONNECT_KEY" > /tmp/apple_key.p8
          
          app-store-connect fetch-signing-files "com.example.sunaaApp" \
            --issuer-id "$APP_STORE_CONNECT_ISSUER_ID" \
            --key-id "$APP_STORE_CONNECT_KEY_ID" \
            --p8-key /tmp/apple_key.p8 \
            --create
          
          keychain add-certificates
          rm /tmp/apple_key.p8
      - name: Get Flutter packages
        script: flutter pub get
      - name: Build iOS IPA
        script: | 
          flutter build ipa --release --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa